version: '3.7'
services:
    pytest:
        build: .
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - test_runner_network
        entrypoint: ["pdm", "run", "pytest"]
networks:
    test_runner_network:
        name: test_runner_network
