version: "3.8"
services:
  pytest:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - test_runner_network
    entrypoint: ["pdm", "run", "pytest"]
  profile:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./profiling/stats:/src/datajoint-link/profiling/stats
    networks:
      - profiling_network
    entrypoint: ["pdm", "run", "python"]
networks:
  profiling_network:
    name: profiling_network
  test_runner_network:
    name: test_runner_network
