[build-system]
requires = ["setuptools >= 40.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 120

[tool.pylint.master]
max-line-length = 120

[tool.coverage.run]
branch = true
source = ["/usr/local/lib/python3.8/dist-packages/dj_link"]

[tool.coverage.report]
exclude_lines = ["if TYPE_CHECKING:"]
