name: Mypy

on: [push, pull_request]

jobs:
  mypy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install Mypy
        run: |
          python -m pip install --upgrade pip
          pip install mypy
      - name: Run Mypy
        run: mypy dj_cleaner